In [7]:
import sys
sys.path.insert(0, '../../../ndreg/')
sys.path.insert(0,'../code/functions/')

import ndreg
import math
import cv2
import pickle

import numpy as np
import SimpleITK as itk
import matplotlib.pyplot as plt
import plosLib as pLib
import connectLib as cLib
import hyperReg as hype

from affine import Affine
from matplotlib import cm
from mpl_toolkits.mplot3d import Axes3D
from random import randrange as rand
from random import uniform as floatRand
from PIL import Image

# Algorithm
## 1. Detailed Pseudocode
**Input Space: ** A cost matrix for two sets of points $P_1$ and $P_2$, where both point sets have identical length $l$

**Output Space: ** An optimal pairing of all $p_1 \in P_1$ with exactly one partner $p_2 \in P_2$ such that $\Sigma \text{Cost}(p_1, p_2)$ is minimized

**Algorithm:**

In [ ]:
######################################
###THIS IS PSEUDOCODE, WILL NOT RUN###
######################################

def hungarian(costMatrix):

p1CostMatrix = costMatrix.copy()
p2CostMatrix = costMatrix.copy().T

#for every point in the first set
for all p1 in p1CostMatrix:
    #find its minimum weighted edge
    minVal = min(costMatrix[p1])
    
    #subtract minimum weight from all edges
    p1CostMatrix[p1] = p1CostMatrix[p1] - minVal

#for every point in the second set
for all p2 in p2CostMatrix:
    #find the minimum weighted edge
    minVal = min(p2CostMatrix[p2])
    
    #subtract the minimum weight from all edges
    p1CostMatrix[p1] = p1CostMatrix[p1] - minVal
    
#generate adjacency matrix of only the 0 weight 
#after the initial 2 steps
initialMatrix = zeros_like(costMatrix)
for y, x in p1CostMatrix.zero():
    initialMatrix[y][x] = 1
    
for y, x, in p2CostMatrix.zero():
    initialMatrix[y][x] = 1
    
#get the maximal matching after the initial step
matching = minimalMatching(initialMatrix)

#if the initialization solves the problem, we are done
if matching.fullRank():
    return matching

#if not, run iterative step until convergence
while not matching.fullRank():
    #get the minimum edge that is not yet paired
    minRemainingWeight = min(matching.rowsWithoutPivot())
    minRemainingP1 = argmin(matching.rowsWithoutPivot())

    #subtract that weight from the remaining graph at that edge
    initialMatrix[minRemainingP1] -= minRemainingWeight
    matching = minimalMatching(initialMatrix)

return matching

## 2. Actual Algorithm Code

In [11]:
#The algorithm can be called with the following
from scipy.optimize import linear_sum_assignment as hungarian
dummyCostMatrix = np.identity(2)
pairing = hungarian(dummyCostMatrix)

## 3. Algorithm Space
### Success Space
Practically, this algorithm will succeed when there is one or a few very similar assignments that minimize the cost funciton.

### Failure Space
Practically, this algorithm will fail when there are multiple differing assignments that minimize the cost function

## 4. Functionality Data Sets
The following two are two data sets with solutions that can be run to ensure the success of the hungarian algorithm in the simple case

In [37]:
funcData1 = np.identity(2)
funcData2 = np.array([[4, 1, 3], [2, 0, 5], [3, 2, 2]])

print 'Data:'
print funcData1
print 'Optimal Pairing:'
print '[[0, 1], [1, 0]]'

print '\nData:'
print funcData2
print 'Optimal Pairing:'
print '[[0, 1], [1, 0], [2, 2]]'

Data:
[[ 1.  0.]
 [ 0.  1.]]
Optimal Pairing:
[[0, 1], [1, 0]]

Data:
[[4 1 3]
 [2 0 5]
 [3 2 2]]
Optimal Pairing:
[[0, 1], [1, 0], [2, 2]]


## 5. Validation Data Set Properties
### Validataion Data 1
This data exists in 2 dimensions with 2 features and should converge after the initialization step. It has exactly 1 optimum pairing

### Validation Data 2
This data exists in 2 dimensions with 3 features. It should converge after at least 1 iterative loop, and has exactly 1 optimum pairing

# 6. Data Visualization Code

In [33]:
def toDiff(imgA, imgB):
    ret = np.empty((imgA.shape[0], imgA.shape[1], 3), dtype=np.uint8)
    for y in range(imgA.shape[0]):
        for x in range(imgA.shape[1]):
            
            if imgA[y][x] and not imgB[y][x]:
                ret[y][x][0] = 255
                ret[y][x][1] = 0
                ret[y][x][2] = 0
            elif not imgA[y][x] and imgB[y][x]:
                ret[y][x][0] = 0
                ret[y][x][1] = 255
                ret[y][x][2] = 0
            elif imgA[y][x] and imgB[y][x]:
                ret[y][x][0] = 255
                ret[y][x][1] = 255
                ret[y][x][2] = 0
            else:
                ret[y][x][0] = 255
                ret[y][x][1] = 255
                ret[y][x][2] = 255
            
    return ret

def visDiff(sliceA, sliceB):
    disp = toDiff(sliceA, sliceB)
    return disp

# Simulation
## 1. Functionality Testing

In [45]:
funcTest1 = zip(*hungarian(funcData1))
funcTest2 = zip(*hungarian(funcData2))

print 'Test1: ', funcTest1 == [(0, 1), (1, 0)]
print '\n\tExpected: ', [(0, 1), (1, 0)]
print '\n\tActual: ', funcTest1
print '\n'
print 'Test2: ', funcTest2 == [(0, 1), (1, 0), (2, 2)]
print '\n\tExpected: ', [(0, 1), (1, 0), (2, 2)]
print '\n\tActual: ', funcTest2

Test1:  True

	Expected:  [(0, 1), (1, 0)]

	Actual:  [(0, 1), (1, 0)]


Test2:  True

	Expected:  [(0, 1), (1, 0), (2, 2)]

	Actual:  [(0, 1), (1, 0), (2, 2)]


Functionality testing had perfect results. This means that the algorithm is ready to move on to the validation testing phase

## 2. Validation Testing
### 1. Get requisite Data

In [46]:
#import the pickled versions of the real data
tp1 = pickle.load(open('../code/tests/synthDat/realDataRaw_t0.synth', 'r'))
tp2 = pickle.load(open('../code/tests/synthDat/realDataRaw_t1.synth', 'r'))

In [47]:
#cut the data to a reasoable size for testing
tp1TestData = tp1[:7]
tp2TestData = tp2[:7]

In [5]:
#run the data through the pipeline
tp1PostPipe = cLib.otsuVox(pLib.pipeline(tp1TestData))
tp2PostPipe = cLib.otsuVox(pLib.pipeline(tp2TestData))

#cut out the ill defined sections
tp1PostPipe = tp1PostPipe[1:6]
tp2PostPipe = tp2PostPipe[1:6]

(5, 1024, 1024)
